services:
  windows:
    image: dockurr/windows
    container_name: windows10
    environment:
      VERSION: "10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389"
    volumes:
      - ./data:/storage
    stop_grace_period: 2m
    restart: unless-stopped
